services:
  proxann-proxy:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
    memswap_limit: 1024M
    env_file:
      - .env
    ports:
      - "0.0.0.0:9094:9094"
    volumes:
      - ${MAINPATH}/config-files/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ${MAINPATH}/config-files/proxy/ProxyNginx.conf:/etc/nginx/conf.d/default.conf
      - ${MAINPATH}/config-files/proxy/certs/fullchain1.pem:/certifcates/cert.crt
      - ${MAINPATH}/config-files/proxy/certs/privkey1.pem:/certifcates/key.key
      - ${MAINPATH}/logs/proxy:/tmp/logs
    networks:
      - proxann-proxy-network

  web:
    #ports:
    #  - '9092:9092'
    networks:
     - proxann-proxy-network

networks:
  proxann-proxy-network:
    name: proxann-proxy-network
    external: true

